### ISSUE TITLE
Redesign da página "Meet the Team"

### ISSUE THREAD

**Issue by fmarquesfilho** [coopera/coopera.github.io#20]
- [x] Remover o texto de cada membro, não está fazendo muito sentido.
- [x] Separá-los por nível: undergrad, masters e alumni
- [x] Deixar links só para o email e Lattes
- [x] Para cada membro, incluir link para projeto que participa (em Projects) -- alguns membros entram no grupo ainda sem um projeto definido, então tem que ser fácil de omitir essa informação sem comprometer o design

**Comment by bernardogfilho** [comment]
Bom, eu não sei quem ainda é membro no laboratório e sei que tem mais pessoas participando. Seria bom atualizarmos isso logo.

Quanto aos projetos, eu também não sei quem está em quê.

**Comment by IgorMarques** [comment]
Igor Marques, Lucas Bibiano, Luiz Rogério, Iago Moreira, Bernardo Gurgel -> TeamTracker

**Comment by bernardogfilho** [comment]
Por exemplo, Iago nem está na página. É preciso que o pessoal que está faltando me dê as informações do nome, email, link pro lattes e se é da graduação, mestrado, etc.

E outra, eu estou usando pegando as fotos de cada membro pelo link do avatar Github. Alguém sugere uma melhor maneira?

**Comment by bernardogfilho** [comment]
Está faltando alguém ainda? Essa issue pode ser fechada?

**Comment by fmarquesfilho** [comment]
Acho que sim, @bernardogfilho !

E muito obrigado mesmo pela ajuda com isso. Aliás, hoje eu abri um chamado pedindo o domínio pro pessoal do IMD.
