### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by fmarquesfilho** [coopera/coopera.github.io#22]
@bernardogfilho tem como voltar o blog?

Agora que os alunos estão publicando seria interessante escrever sobre cada avanço do grupo em um blog.

Minha dúvida é: colocamos o blog na página principal ou fazemos uma página separada pra ele?

**Comment by bernardogfilho** [comment]
Acho que pode ser uma página separada.

**Comment by fmarquesfilho** [comment]
OK, então façamos em uma página separada. :)
